version: "3.8"
x-custom:
  gcp:
    - &gcp_project_id "dummy"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/data:/data
  terraform:
     container_name: zaim-terraform
     build:
       context: ./terraform
       dockerfile: Dockerfile
     working_dir: /terraform
     tty: true
     volumes:
       - ./terraform:/terraform:cached
       - /var/run/docker.sock:/var/run/docker.sock
     entrypoint: bash
     environment:
       HOME: "/terraform"
