version: "3.8"

services:
  db:
    container_name: zaim-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: zaim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./server/database/data:/var/lib/postgresql/data
