# https://taskfile.dev

version: '3'

includes:
  terraform:
    taskfile: ./task/Terraform.yaml
    dir: ./task
  docker:
    taskfile: ./task/Docker.yaml
    dir: ./task

tasks:
  generate:
    dotenv: ['.env']
    dir: ./server
    cmds:
      - go run cmd/bun/migrate/main.go
  test:
    dotenv: ['.env']
    dir: ./server
    cmds:
      - go test ./...
