# https://taskfile.dev

version: '3'

tasks:
  docker-up:
    cmds:
      - docker compose up -d
  docker-build:
    cmds:
      - docker compose build
  docker-down:
    cmds:
      - docker compose down
  docker-ps:
    cmds:
      - docker compose ps
  terraform-init:
    cmds:
      - docker compose exec terraform terraform init
  terraform-upgrade:
    cmds:
      - docker compose exec terraform terraform init -upgrade
  terraform-plan:
    cmds:
      - docker compose exec terraform terraform plan
  terraform-apply:
    cmds:
      - docker compose exec terraform terraform apply
  terraform-check:
    cmds:
      - docker compose exec terraform terraform fmt -recursive
      - docker compose exec terraform terraform fmt -recursive -check
      - docker compose exec terraform terraform validate -no-color
      - docker compose exec terraform tfsec .
      - docker compose exec terraform tflint
