apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zaim-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      containers:
        - image: asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:latest
  traffic:
    - latestRevision: true
      percent: 100
