name: 'Build App'

on:
  pull_request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/137094135185/locations/global/workloadIdentityPools/gh-oidc-pool/providers/github-actions'
          service_account: 'github-actions@kanade0404.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - run: ls -la

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./server/go.mod

      - name: Download Go Modules
        run: go mod download

      - name: Test
        run: go test -v ./...

      - name: Build Go
        run: go build -o ./bin/zaim-api ./cmd/zaim/main.go

      - name: Build Docker
        run: docker build -t asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:${{ github.sha }} .

      - name: Push Docker
        run: docker push asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:${{ github.sha }}
