name: 'Deploy App'

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: read
    id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/137094135185/locations/global/workloadIdentityPools/gh-oidc-pool/providers/github-actions'
          service_account: 'github-actions@kanade0404.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker
        run: docker build -t asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:${{ github.sha }} .

      - name: Push Docker
        run: docker push asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:${{ github.sha }}

      - name: Deploy Docker
        run: |
          gcloud run deploy zaim-api \
          --project=kanade0404 \
          --image asia-northeast1-docker.pkg.dev/kanade0404/zaim-api/app:${{ github.sha }} \
          --service-account zaim-func \
          --platform=managed \
          --region=asia-northeast1
