name: 'Plan Terraform'

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/plan_terraform.yaml'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WORKING_DIRECTORY: ./terraform

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.1.7'
        with:
          workload_identity_provider: 'projects/137094135185/locations/global/workloadIdentityPools/gh-oidc-pool/providers/github-actions'
          service_account: 'github-actions@kanade0404.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: aquaproj/aqua-installer@v3.1.0
        with:
          aqua_version: v2.28.0
          working_directory: ${{ env.WORKING_DIRECTORY }}

      - name: Decrypt terraform.tfvars
        run: gcloud kms decrypt --location "asia-northeast1" --keyring "infra" --key "infra" --plaintext-file ./terraform.tfvars --ciphertext-file ./terraform.tfvars.enc

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: tflint
        uses: reviewdog/action-tflint@v1.23.2
        with:
          github_token: ${{ secrets.github_token }}

      - name: Check tfsec
        run: trivy config --severity HIGH,CRITICAL .

      - name: Terraform Plan
        run: tfcmt plan -patch -- terraform plan -no-color -input=false
