name: 'Plan Terraform'

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WORKING_DIRECTORY: ./terraform

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/137094135185/locations/global/workloadIdentityPools/gh-oidc-pool/providers/github-actions'
          service_account: 'github-actions@kanade0404.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4
          working_directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: tflint
        uses: reviewdog/action-tflint@v1.20.0
        with:
          github_token: ${{ secrets.github_token }}

      - name: Check tfsec
        run: tfsec .
        continue-on-error: true

      - name: Terraform Plan
        run: tfcmt plan -patch -- terraform plan -no-color -input=false -var='PROJECT_ID=${{ secrets.TF_PROJECT_ID }}' -var='USERS_SECRET=${{ secrets.TF_USERS_SECRET }}'
